"""new fields

Revision ID: 1cf0a35df4e6
Revises: 14a4c47dec96
Create Date: 2024-05-07 22:36:19.839354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf0a35df4e6'
down_revision = '14a4c47dec96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_name', sa.String(), nullable=True))
        batch_op.drop_column('picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('picture_name')

    # ### end Alembic commands ###
