"""empty message

Revision ID: 2a3e23ae5b9e
Revises: af102d09b96a
Create Date: 2024-05-11 18:31:31.895432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3e23ae5b9e'
down_revision = 'af102d09b96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maxslider', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('sold_price', sa.Float(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('sold_price')
        batch_op.drop_column('maxslider')

    # ### end Alembic commands ###
