"""less fields in post model

Revision ID: 5102af635859
Revises: ae94cbc9d395
Create Date: 2024-05-07 13:41:55.259030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5102af635859'
down_revision = 'ae94cbc9d395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('photo_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_filename', sa.VARCHAR(length=200), nullable=False))

    # ### end Alembic commands ###
