"""newwer fields in Posts

Revision ID: 5e944e15df70
Revises: 1cf0a35df4e6
Create Date: 2024-05-07 22:40:20.509304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e944e15df70'
down_revision = '1cf0a35df4e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('data')

    # ### end Alembic commands ###
