"""New Class table called Guess

Revision ID: 76f896c40136
Revises: 2a3e23ae5b9e
Create Date: 2024-05-11 20:16:14.410630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f896c40136'
down_revision = '2a3e23ae5b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('guessed_price', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guess', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guess_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guess', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guess_timestamp'))

    op.drop_table('guess')
    # ### end Alembic commands ###
