"""new fields in post model

Revision ID: ae94cbc9d395
Revises: 927f9d157018
Create Date: 2024-05-07 13:22:20.497792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae94cbc9d395'
down_revision = '927f9d157018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=280), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('condition', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('starting_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('photo_filename', sa.String(length=200), nullable=False))
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=140), nullable=False))
        batch_op.drop_column('photo_filename')
        batch_op.drop_column('starting_price')
        batch_op.drop_column('condition')
        batch_op.drop_column('category')
        batch_op.drop_column('description')
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
