"""New maxslider in Post

Revision ID: af102d09b96a
Revises: a9bdf7ee12fb
Create Date: 2024-05-10 22:30:37.845504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af102d09b96a'
down_revision = 'a9bdf7ee12fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maxslider', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('maxslider')

    # ### end Alembic commands ###
