"""empty message

Revision ID: d178d348494a
Revises: e870f3c2d988
Create Date: 2024-05-12 02:33:32.678255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd178d348494a'
down_revision = 'e870f3c2d988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mimetype', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mimetype')
        batch_op.drop_column('img')
        batch_op.drop_column('picture_name')

    # ### end Alembic commands ###
