"""newer functions within Post

Revision ID: d323aaaaa336
Revises: 5e944e15df70
Create Date: 2024-05-07 23:16:36.925352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd323aaaaa336'
down_revision = '5e944e15df70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimetype', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('mimetype')

    # ### end Alembic commands ###
