"""Changes to names of functions

Revision ID: e01693e657b6
Revises: d323aaaaa336
Create Date: 2024-05-07 23:18:03.438689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e01693e657b6'
down_revision = 'd323aaaaa336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(), nullable=True))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('img')

    # ### end Alembic commands ###
